config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  post '/books' => 'books#create'

  get '/books' => 'books#index'

  get '/books/:id' => 'books#show', as: 'book'

  get '/books/:id/edit' => 'books#edit', as: 'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete '/books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save
       flash[:notice] = "Book was successfully created"
       redirect_to book_path(@book)
    else
       @books = Book.all
       render :index
    end
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book was successfully updated"
       redirect_to book_path(@book)
    else
       render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
  params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book) do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %><br>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to 'Show', book_path(@book) %>
<span>|</span>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h2>Books</h2>

<table>

  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
      	<%= book.title %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', destroy_book_path(book), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>

</table>

<h3>New book</h3>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book) do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<h3><strong>Title:</strong> <%= @book.title %></h3>

<h3><strong>Body:</strong> <%= @book.body %></h3>

<%= link_to 'Edit', edit_book_path(@book) %>
<span>|</span>
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<h2>ようこそ　Bookersへ！</h2>

<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>

<%= link_to 'start', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rebookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>